name: cicd

on:
  push:
    paths:
        - src/**
    branches:
        - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten the commit id to first 6 characters
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aumthakkar/python-app:${{ env.COMMIT_ID }}
    
    outputs:
      commit_id: ${{ env.COMMIT_ID }}


  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3 # This step clones our argocd synced github repo first before committing to our values.yaml file below

      - name: Update Image tag in argocd monitored charts/python-app/values.yaml file on github
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates charts/python-app/values.yaml with latest docker image push commit ${{needs.ci.outputs.commit_id}}'

      - name: Install Argocd # To run the argocd app sync <application> argocd CLI 
        shell: bash
        run: |
          curl -ksSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
          
      - name: Argocd app sync
        shell: bash
        run: |        
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }}  

          argocd app sync python-app 

